### ISSUE TITLE
Crash on Forge 1899

### ISSUE THREAD

**Issue by asiekierka** [iTitus/RecStat#1]
java.lang.IllegalAccessError: tried to access field net.minecraftforge.event.entity.living.LivingEvent.entityLiving from class io.github.ititus.recstat.handler.EventHandler
    at io.github.ititus.recstat.handler.EventHandler.onPlayerUpdate(EventHandler.java:67)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_96_EventHandler_onPlayerUpdate_LivingUpdateEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:469)
    at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1879)
    at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:296)
    at net.minecraft.world.World.func_72866_a(World.java:1934)
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:836)
    at net.minecraft.world.World.func_72870_g(World.java:1903)
    at net.minecraft.world.World.func_72939_s(World.java:1737)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:705)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:609)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:148)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:467)
    at java.lang.Thread.run(Thread.java:745)

**Comment by iTitus** [comment]
Oh. I think I need to update Forge.
Will do so in ~30 mins.

**Comment by iTitus** [comment]
Fixed in 2.1.2
